import type { Agent, MandatePlan } from "./types";

export const MANDATE_BOTS: Agent[] = [
  {
    id: "audit",
    name: "Audit",
    desk: "mandate",
    vertical: "IB-Pläne",
    status: "done",
    lastRun: "2026-08-21T10:32:00.000Z",
    summary:
      "Sechs Häuser gelesen: Goldman High-Quality, JPM 60/40, MS AI-Leaders, UBS Swiss Income, Vanguard Target, BlackRock iShares Core. Zwei systematische Fehler: Duration-Blindheit und AI-Konzentration ohne Zahler.",
  },
  {
    id: "scout",
    name: "Scout",
    desk: "mandate",
    vertical: "Korrektur",
    status: "done",
    lastRun: "2026-08-21T10:35:00.000Z",
    summary:
      "Jeder Plan bekommt eine Korrektur, die den 350-€-Boden füllt: TLT-Sleeve kappen, Zahler (JPM, GS, AVGO, UNH, BLK) rein, Kern SPY/VOO nicht unter 35 %.",
  },
  {
    id: "score",
    name: "Score",
    desk: "mandate",
    vertical: "10J-Quote",
    status: "done",
    lastRun: "2026-08-21T10:38:00.000Z",
    summary:
      "Zehn Jahre, wöchentlich. Trefferquote = Anteil der Jahre über SPY. MS AI-Leaders schlägt SPY in 6/10, verliert 2022 −28 %. Korrigiert: 7/10, Drawdown −16 %. In die Trading-Demo.",
  },
];

export const MANDATE_PLANS: MandatePlan[] = [
  {
    id: "gs-hq",
    house: "Goldman Sachs",
    title: "High-Quality Compounders",
    published: "2026-07-14",
    universe: ["MSFT", "AAPL", "GOOGL", "V", "UNH", "COST"],
    thesis: "Qualität, Pricing-Power, niedriger Turnover. Kein Krypto, kein Small-Cap.",
    flaws: [
      "Kein Zahler-Tilt — UNH ist der einzige Dividenden-Anker.",
      "Kein S&P-Kern. Drawdown 2022 ohne Ballast.",
      "V/COST nicht im Book, doppelte Konsum-Duration.",
    ],
    fix: "35 % SPY/VOO, 15 % BLK, Overlay nur MSFT/AAPL/UNH plus JPM. COST und V raus — zahlen den 350-€-Boden nicht.",
    hitRate10y: 60,
    cagr10y: 12.4,
    spyCagr10y: 13.1,
    maxDd: -24.8,
    improvedCagr: 13.6,
    improvedHit: 70,
    status: "scored",
  },
  {
    id: "jpm-6040",
    house: "J.P. Morgan",
    title: "60/40 Multi-Asset",
    published: "2026-06-02",
    universe: ["SPY", "TLT", "GLD", "EEM"],
    thesis: "Klassiker. 60 Aktien, 40 Bonds, Gold und EM als Satelliten.",
    flaws: [
      "TLT 40 % hat 2022 und 2025 den Boden gerissen.",
      "Keine Ausschüttung aus Overlay — 60/40 Yield ~2 %, zu dünn für 350 € auf 26k.",
      "EEM-Satellit ohne Filter, EM-Drawdowns fressen den Monat.",
    ],
    fix: "Bonds auf 10 % TLT. 35 % SPY/VOO, 15 % BLK, 40 % Overlay-Zahler. Gold nur als 5-%-Hedge, nicht als Alpha.",
    hitRate10y: 40,
    cagr10y: 7.8,
    spyCagr10y: 13.1,
    maxDd: -21.4,
    improvedCagr: 11.9,
    improvedHit: 60,
    status: "sent",
    trialId: "tt-jpm",
  },
  {
    id: "ms-ai",
    house: "Morgan Stanley",
    title: "AI Leaders Basket",
    published: "2026-08-04",
    universe: ["NVDA", "AVGO", "MSFT", "GOOGL", "META", "TSM"],
    thesis: "Kapazität, Inference, Cloud. Kein Value, kein Finanz.",
    flaws: [
      "Sechs Namen, eine Duration. 2022 −28 %.",
      "TSM nicht im Book, ADR-Spread.",
      "Null Ausschüttung außer AVGO. Boden hängt an einem Print.",
    ],
    fix: "AI-Sleeve 18 % (NVDA 6, AVGO 10, MSFT 2). Rest Kern + Zahler. META nicht nach RL-Verlust addieren.",
    hitRate10y: 60,
    cagr10y: 18.2,
    spyCagr10y: 13.1,
    maxDd: -28.1,
    improvedCagr: 15.4,
    improvedHit: 70,
    status: "review",
  },
  {
    id: "ubs-inc",
    house: "UBS",
    title: "Swiss Income",
    published: "2026-05-20",
    universe: ["NESN", "ROG", "NOVN", "ZURN", "TLT"],
    thesis: "Dividenden-Aristokraten Schweiz plus Duration.",
    flaws: [
      "Keine US-Zahler. CHF-FX frisst Euro-Ausschüttung.",
      "Pharma-Klumpen ohne UNH-Hedge.",
      "Nicht handelbar 1:1 im Paper — ADR-Spread.",
    ],
    fix: "These behalten, Vehikel tauschen: UNH + JPM + GS + BLK statt Swiss-Names. TLT auf 5 %.",
    hitRate10y: 50,
    cagr10y: 8.1,
    spyCagr10y: 13.1,
    maxDd: -18.6,
    improvedCagr: 12.2,
    improvedHit: 60,
    status: "review",
  },
  {
    id: "vg-tr",
    house: "Vanguard",
    title: "Target Retirement 2045",
    published: "2026-01-15",
    universe: ["VOO", "VXUS", "BND", "BNDX"],
    thesis: "Passiv, billig, Gleitpfad. Das ist der Kern, nicht das Overlay.",
    flaws: [
      "BND/BNDX 20 %+ — Yield deckt den Boden nicht.",
      "VXUS ohne Filter. Europa/Japan ohne BLK-Tollbooth.",
      "Kein aktiver Overlay — 350 € nur über Größe, nicht über Quote.",
    ],
    fix: "VOO behalten (13 %). SPY dazu (22 %). BND raus. Overlay 50 % Zahler. Das ist unser Kern-Satellit, nur ohne den Bond-Ballast.",
    hitRate10y: 50,
    cagr10y: 9.6,
    spyCagr10y: 13.1,
    maxDd: -19.2,
    improvedCagr: 13.4,
    improvedHit: 70,
    status: "applied",
  },
  {
    id: "blk-core",
    house: "BlackRock",
    title: "iShares Core Allocation",
    published: "2026-03-11",
    universe: ["IVV", "IUSB", "IEMG", "IEFA"],
    thesis: "AUM-Maschine. IVV ≈ SPY, IUSB Bonds, EM/EAFE Satelliten.",
    flaws: [
      "Sponsor verkauft die Hülle, nicht die Ausschüttung.",
      "IUSB gleiche Duration-Falle wie TLT-light.",
      "BLK-Aktie selbst fehlt — Tollbooth nicht im eigenen Modell.",
    ],
    fix: "IVV durch SPY+VOO ersetzen. IUSB raus. BLK 15 % als Tollbooth auf denselben Flow. Overlay Zahler.",
    hitRate10y: 50,
    cagr10y: 9.9,
    spyCagr10y: 13.1,
    maxDd: -20.1,
    improvedCagr: 13.8,
    improvedHit: 70,
    status: "scored",
  },
];
