import type {
  AlertItem,
  EarningsNote,
  Filing,
  Lesson,
  MacroEvent,
  MorningBrief,
  OpsTask,
  SentimentRow,
  WeeklyBrief,
  WhalePosition,
} from "./types";

export const MORNING_BRIEF: MorningBrief = {
  id: "brief-2026-08-21",
  deliveredAt: "2026-08-21T10:00:00.000Z",
  title: "Freitagbuch — Kern steht, Overlay verdient den Rest",
  lede: "Overnight über Filings, Earnings, Sektor, Sentiment, Insider und Koordination. Testlauf 300 Dollar Paper. Duales Mandat: Cash diesen Monat, Kapital über 90 Tage. Book auf 15 Namen, kein Echtgeld.",
  sections: [
    {
      heading: "Strategie",
      tickers: ["SPY", "VOO", "BLK"],
      body: "Kern-Satellit ist live. 300 Dollar Testlauf, Gewinn bleibt im Book. 35 % S&P über SPY/VOO, 15 % BLK, 50 % Beimischung mit Tilt auf Zahler — Gewichte folgen dem Tape. Relativverlust vs SPY nach 90 Tagen unter 5 %. Jackson-Hole-Woche: Kern nicht anfassen.",
    },
    {
      heading: "Filings",
      tickers: ["NVDA", "META", "AVGO", "BLK"],
      body: "NVIDIA 8-K: Take-or-pay, 6,2 Mrd. reservierte Wafer. Metas 10-Q: Reality-Labs-Verlust 4,8 Mrd. Broadcom-Form-4-Cluster. BlackRock 10-Q: iShares-AUM +9 % q/q, Fee-Rate stabil — das rechtfertigt die 15-%-Sleeve.",
    },
    {
      heading: "Earnings",
      tickers: ["AVGO", "UNH", "LLY"],
      body: "Broadcom sauber geschlagen, FY-Guide +2,4 Mrd. UnitedHealth MCR-Miss, Guide steht. Lilly EPS-Beat, orale GLP-1-Kapazität konstruktiv. Overlay verdient hier; der Kern nicht anfassen.",
    },
    {
      heading: "Sentiment",
      tickers: ["TSLA", "META"],
      body: "Tesla-Mentions +3,4σ — Robotaxi-Clips, kein Filing. Forge hat das als Demo-Fehler W32 markiert. Nicht nachlaufen. Meta-Ton nach Reality Labs gekippt.",
    },
    {
      heading: "Institutionelle Flows",
      tickers: ["LLY", "UNH", "NVDA", "SPY"],
      body: "Citadel LLY-Initiation, Millennium LLY +27 %, Tiger +39 %. Two Sigma UNH −31 %. BlackRock und Vanguard stocken SPY/VOO-nahe Mega-Caps, kein Exit aus dem Kern. Cluster-Buying bleibt ein Einnahmen-Signal, kein Lizenz zum Nachlaufen.",
    },
    {
      heading: "Makro",
      tickers: ["NVDA", "AVGO", "SPY"],
      body: "Jackson Hole Montag. Semis implizit 2,4 % hawkish, 1,1 % hold. SPY/VOO sind der Ballast; Overlay-Adds erst nach der Rede, nicht davor.",
    },
  ],
  actions: [
    {
      ticker: "SPY",
      action: "Kern halten, 22 %",
      rationale: "Liquider S&P-500. Benchmark und Hedge. Kein Trim in einer Event-Woche.",
    },
    {
      ticker: "VOO",
      action: "Kern halten, 13 %",
      rationale: "Vanguard-Vehikel. Tracking gegen SPY beobachten, nicht als Alpha verbuchen.",
    },
    {
      ticker: "BLK",
      action: "15 % stehen lassen",
      rationale: "AUM-Leverage auf denselben Passiv-Flow. Add nur, wenn iShares-Zuflüsse weiter laufen.",
    },
    {
      ticker: "AVGO",
      action: "Auf Schwäche addieren",
      rationale: "Guide-Anhebung + Insider-Cluster. 1,0–1,5 % Overlay, falls Jackson Hole risk-off öffnet — nur wenn Demo-Woche grün.",
    },
    {
      ticker: "UNH",
      action: "40 bp trimmen",
      rationale: "MCR-Miss, Two-Sigma-Distribution. Kernposition halten.",
    },
    {
      ticker: "TSLA",
      action: "Nicht nachlaufen",
      rationale: "W32-Demo hat denselben Trade verbrannt. Bestand 0,5 %. Lesson applied.",
    },
  ],
};

export const WEEKLY_BRIEF: WeeklyBrief = {
  id: "weekly-2026-w34",
  weekOf: "2026-08-17",
  deliveredAt: "2026-08-21T10:30:00.000Z",
  title: "Weekly · Woche 34 — Boden, Dual, Profile",
  lede: "Testlauf 300 Dollar Paper. Lehrwochen W33/W34 sind Beispiele, keine Entnahme. Duales Mandat: Cash diesen Monat, Kapital über 90 Tage. Profilvorschläge aller Teams hängen an diesem Brief.",
  revenue: {
    bookPct: 1.7,
    spyPct: 1.4,
    note: "Lehrwochen W33/W34 sind Beispiele, hochgerechnet, nicht gebucht. Nachweis 350 € netto auf 26.000 € digital, gezahlt aus Beimischung plus Dividende. Relativ im 5-%-Limit. Unter der Projektion: Abbruch.",
  },
  feedback: [
    {
      bot: "Forge",
      heading: "Post-Mortem",
      body: "W32: Overlay hat TSLA auf +3σ-Sentiment geöffnet. Kein Filing, kein Print, Demo −0,6 % gegen SPY +0,2 % — und null Ausschüttung. Regel hart: Sentiment ohne Ledger- oder Callbook-Bestätigung ist kein Entry. UNH-Trim kam einen Sitzungstag nach dem Two-Sigma-13F. Zahler nicht weiter kürzen, die 350 € brauchen die Dividende.",
    },
    {
      bot: "Gauge",
      heading: "Effizienz",
      body: "Doppel-Alerts Pulse/Ledger zu TSLA und NVDA, 12 Minuten Floor-Lärm, null zusätzliche Einnahmen. Throttle: ein Alert pro Ticker in vier Stunden, Helmsman dedupliziert. FactSet-Seat 14.200 $ — Gauge hält die Kündigung, sobald Filings+Flows ein Quartal stehen. Overnight-Lauf 9 Bots in Serie: Feedback-Team parallel zu Helmsman-Kompilat, spart ~2 Minuten und eine Modell-Runde.",
    },
    {
      bot: "Canon",
      heading: "Inklusionsplan Woche 35",
      body: "Alles, was diese Woche gelernt wurde, geht nur live, wenn es den 350-€-Boden füllt. Abbruch-Schwelle in Kommando. Chart-Desk und Universum Pflicht vor Overlay-Add. Trading-Demo vor IB-Korrektur. Overlay-Tilt JPM/GS/AVGO/UNH. Profilvorschläge aller Teams in diesem Brief. Kein Prozess ohne Owner und ETA.",
    },
  ],
  dual: {
    cashNote:
      "Diesen Monat: Paper 300 $. Zahler zuerst. Kein TSLA, kein Gold im Monat.",
    capitalNote:
      "90-Tage-Programm bis 23. Nov: Relativverlust vs SPY unter 5 %. Kern SPY/VOO/BLK unangetastet. Stretch 700 € erst, wenn der Boden drei Monate steht.",
  },
  proposals: [
    {
      id: "pp-1",
      team: "trade",
      kind: "add",
      profile: "Vein / overlooked insides",
      rationale: "ASIC-Threads und URTH-Flow waren nicht im Research-Raster. Profil behalten.",
      owner: "edict",
      status: "applied",
    },
    {
      id: "pp-2",
      team: "trade",
      kind: "remove",
      profile: "Discretionary-Konsum-Sleeve",
      rationale: "Cart sieht Delinquenz. AAPL/AMZN zahlen den Boden nicht.",
      owner: "cart",
      status: "applied",
    },
    {
      id: "pp-3",
      team: "mandate",
      kind: "expand",
      profile: "Broker-Modellportfolios (Schwab, Fidelity)",
      rationale: "IB-Seite steht. Broker-Target-Date fehlt.",
      owner: "scout",
      status: "discuss",
    },
    {
      id: "pp-4",
      team: "research",
      kind: "trim",
      profile: "Pulse-TSLA-Mentions",
      rationale: "Signal deckt denselben Spike. Doppel prüfen.",
      owner: "caliper",
      status: "discuss",
    },
    {
      id: "pp-5",
      team: "feedback",
      kind: "add",
      profile: "Abbruch-Schwelle im Weekly",
      rationale: "Canon schreibt die 350-€-Projektion als Go/No-Go.",
      owner: "canon",
      status: "queued",
    },
    {
      id: "pp-6",
      team: "feedback",
      kind: "remove",
      profile: "FactSet-Seat",
      rationale: "Gauge hält die Kündigung.",
      owner: "gauge",
      status: "queued",
    },
  ],
  inclusion: [
    { item: "350 € ist Abbruchschwelle, nicht Wunsch", owner: "Skipper", eta: "So 23.08.", status: "applied" },
    { item: "Stretch 700 / Horizont 1.500 in Kommando", owner: "Canon", eta: "So 23.08.", status: "applied" },
    { item: "Duales Mandat Cash-jetzt vs Kapital im Weekly", owner: "Helmsman", eta: "So 23.08.", status: "applied" },
    { item: "Universum-Desk 10J inkl. BTC/GLD/URTH", owner: "Drift", eta: "Mo 06:00 MET", status: "drafted" },
    { item: "Mandat-Team Audit/Scout/Score gegen IB-Pläne", owner: "Audit", eta: "Mo Open", status: "applied" },
    { item: "Trading-Floor mit Skipper, Feedback, eigener Demo", owner: "Skipper", eta: "So 23.08.", status: "applied" },
    { item: "Profilvorschläge aller Teams im Weekly", owner: "Edict", eta: "So 23.08.", status: "applied" },
    { item: "Overlay-Tilt Zahler JPM/GS/AVGO/UNH", owner: "Meridian", eta: "Mo Open", status: "drafted" },
    { item: "7×24h-Demo vor NVDA-Print", owner: "Forge", eta: "Mi Close", status: "queued" },
    { item: "Broker-Modelle Schwab/Fidelity lesen", owner: "Scout", eta: "Fr 29.08.", status: "queued" },
    { item: "Take-Profit der Beimischung jede Sekunde", owner: "Till / Drift", eta: "Autopilot", status: "applied" },
    { item: "Verlierer unter −2,2 pp flach", owner: "Forge", eta: "Autopilot", status: "applied" },
  ],
};

export const LESSONS: Lesson[] = [
  {
    id: "l1",
    week: "W32",
    source: "demo",
    mistake: "TSLA auf X-Volumen +3σ geöffnet. Kein Filing, kein Print. Demo −0,6 %.",
    fix: "Sentiment ohne Ledger- oder Callbook-Bestätigung ist kein Entry. Overlay-Size 0 auf reine Mention-Spikes.",
    owner: "forge",
    status: "applied",
    tickers: ["TSLA"],
    effect: "ban",
  },
  {
    id: "l2",
    week: "W33",
    source: "live",
    mistake: "UNH-Trim einen Tag nach Two-Sigma-13F. 40 bp später, Kurs schon −1,1 %.",
    fix: "Shadow übergibt materielle 13F-Moves intra-day an Helmsman, nicht erst über Nacht.",
    owner: "canon",
    status: "open",
    tickers: ["UNH"],
    effect: "trim",
  },
  {
    id: "l3",
    week: "W31",
    source: "demo",
    mistake: "Tracking-Spread SPY vs. VOO als Alpha verbucht. 4 bp, die keine Einnahme sind.",
    fix: "Spread zwischen den beiden Kern-ETFs ist Rauschen. Nur BLK- und Overlay-Spread zählt als verdient.",
    owner: "gauge",
    status: "applied",
  },
  {
    id: "l4",
    week: "W34",
    source: "bot",
    mistake: "Pulse und Ledger haben denselben NVDA-Satz zweimal auf den Floor gedrückt.",
    fix: "Helmsman dedupliziert. Ein Alert pro Ticker in vier Stunden.",
    owner: "gauge",
    status: "applied",
  },
  {
    id: "l5",
    week: "W34",
    source: "demo",
    mistake: "Overlay-Add ohne Blick auf den Chart-Desk. Einstieg 1,2 % über dem Intraday-Tief.",
    fix: "Vor jedem Overlay-Add Chart-Desk 1W/1M. Kein Add über dem Tageshoch der letzten drei Sitzungen.",
    owner: "forge",
    status: "open",
  },
];

export const ALERTS: AlertItem[] = [
  {
    id: "a1",
    ts: "2026-08-21T09:12:00.000Z",
    desk: "filings",
    severity: "material",
    ticker: "NVDA",
    headline: "NVDA 8-K — 6,2 Mrd. Take-or-pay-Kapazität",
    body: "Sprache gegenüber unverbindlichen Forecasts verschärft. Materieller Unterschied zum vorigen 10-Q.",
  },
  {
    id: "a2",
    ts: "2026-08-21T08:44:00.000Z",
    desk: "sentiment",
    severity: "watch",
    ticker: "TSLA",
    headline: "TSLA-Mentions +3,4σ gegen 30-Tage-Baseline",
    body: "Cluster unüberwachter Robotaxi-Clips. Nur Flag. Forge: nicht als Entry.",
  },
  {
    id: "a3",
    ts: "2026-08-21T07:18:00.000Z",
    desk: "flows",
    severity: "material",
    ticker: "LLY",
    headline: "Cluster-Kauf: Citadel initiiert, Millennium +27 %",
    body: "Drei Fonds ziehen bei LLY mit. Historisches Cluster-Buy-Alpha rund 5,3 % annualisiert.",
  },
  {
    id: "a8",
    ts: "2026-08-21T10:32:00.000Z",
    desk: "feedback",
    severity: "info",
    headline: "Weekly 34 kompiliert — Forge, Gauge, Canon",
    body: "Book +1,7 % gegen SPY +1,4 %. Inklusionsplan Woche 35 liegt im Brief. Zwei offene Lessons.",
  },
  {
    id: "a9",
    ts: "2026-08-21T10:40:00.000Z",
    desk: "charts",
    severity: "info",
    ticker: "BLK",
    headline: "BLK/SPY/VOO im Book — Kern-Satellit live",
    body: "35 % S&P-Kern, 15 % BlackRock-Tollbooth, 50 % Overlay. Vanguard über VOO.",
  },
  {
    id: "a4",
    ts: "2026-08-21T06:55:00.000Z",
    desk: "earnings",
    severity: "watch",
    ticker: "UNH",
    headline: "UNH MCR-Miss — CFO-Ton defensiv",
    body: "Guide bestätigt. Q&A stark auf Medicare-Advantage-Utilization.",
  },
  {
    id: "a5",
    ts: "2026-08-21T06:22:00.000Z",
    desk: "filings",
    severity: "info",
    ticker: "AVGO",
    headline: "AVGO Form-4-Cluster — drei Direktoren",
    body: "Open-Market-Käufe, keine Optionsausübungen. Shadow wertet das als echte Nachfrage.",
  },
  {
    id: "a6",
    ts: "2026-08-20T21:04:00.000Z",
    desk: "macro",
    severity: "watch",
    headline: "Jackson Hole öffnet Montag — Semis implizit 2,4 %",
    body: "Chair-Rede Freitag 16:00 MET. Kern (SPY/VOO) halten, Overlay erst nach der Rede.",
  },
  {
    id: "a7",
    ts: "2026-08-20T18:30:00.000Z",
    desk: "ops",
    severity: "info",
    headline: "LP-Brief-Entwurf wartet auf Helmsman",
    body: "August-Monatsende-Pack. Erste Zeile: Einnahmen vs. SPY.",
  },
];

export const FILINGS: Filing[] = [
  {
    id: "f1",
    ticker: "NVDA",
    form: "8-K",
    filedAt: "2026-08-20T21:14:00.000Z",
    title: "Abschluss eines wesentlichen Vertrags — reservierte Wafer-Kapazität",
    material: true,
    delta: "Take-or-pay-Sprache; 6,2 Mrd. reserviert. Voriger 10-Q sprach nur von unverbindlichen Forecasts.",
    accession: "0001045810-26-000188",
  },
  {
    id: "f2",
    ticker: "META",
    form: "10-Q",
    filedAt: "2026-08-01T20:06:00.000Z",
    title: "Quartalsbericht — Reality Labs und Ads-Mix",
    material: true,
    delta: "Reality-Labs-Verlust 4,8 Mrd. (zuvor 5,1 Mrd.). Ads-Attach +40 bp. Capex-Guide unverändert.",
    accession: "0001326801-26-000094",
  },
  {
    id: "f3",
    ticker: "AVGO",
    form: "4",
    filedAt: "2026-08-19T22:41:00.000Z",
    title: "Änderung des wirtschaftlichen Eigentums — Direktoren-Cluster",
    material: true,
    delta: "Drei unabhängige Direktoren kauften im 48-Stunden-Fenster. Open Market, keine Optionen.",
    accession: "0001730168-26-000221",
  },
  {
    id: "f11",
    ticker: "BLK",
    form: "10-Q",
    filedAt: "2026-08-08T20:12:00.000Z",
    title: "Quartalsbericht — iShares-AUM und Fee-Rate",
    material: true,
    delta: "iShares-AUM +9 % q/q. Fee-Rate stabil. Performance-Fees saisonal dünn. Tollbooth-These intakt.",
    accession: "0001364742-26-000074",
  },
  {
    id: "f4",
    ticker: "AAPL",
    form: "10-Q",
    filedAt: "2026-08-01T20:18:00.000Z",
    title: "Quartalsbericht — Services-Mix und China",
    material: false,
    delta: "Services +14 % y/y. Greater China −3 %. Bruttomarge im Rahmen. Keine neue Buyback-Ermächtigung.",
    accession: "0000320193-26-000077",
  },
  {
    id: "f5",
    ticker: "TSLA",
    form: "8-K",
    filedAt: "2026-08-12T21:02:00.000Z",
    title: "Regulation FD — begrenzter unüberwachter Robotaxi-Rollout",
    material: true,
    delta: "Bestätigt unüberwachte Geofences in Austin und der Bay Area. Kein Volumen und kein Zeitplan über „dieses Jahr“ hinaus.",
    accession: "0001318605-26-000156",
  },
  {
    id: "f6",
    ticker: "JPM",
    form: "10-Q",
    filedAt: "2026-08-05T20:11:00.000Z",
    title: "Quartalsbericht — Zinsergebnis und Kredit",
    material: false,
    delta: "NII-Guide um 400 Mio. gekürzt. Kreditqualität bleibt gutartig. CET1 15,4 %.",
    accession: "0000019617-26-000201",
  },
  {
    id: "f7",
    ticker: "UNH",
    form: "8-K",
    filedAt: "2026-08-15T12:04:00.000Z",
    title: "Operatives Ergebnis und Finanzlage",
    material: true,
    delta: "MCR 88,4 gegen 86,9 Konsens. FY-Guide bestätigt. MA-Utilization als „persistent“ bezeichnet.",
    accession: "0000731766-26-000119",
  },
  {
    id: "f8",
    ticker: "GS",
    form: "13F-HR",
    filedAt: "2026-08-14T21:55:00.000Z",
    title: "Quartalsweiser Bestandsbericht",
    material: false,
    delta: "Asset-Management-13F. Book-Overlap nur bei NVDA und MSFT; keine neuen Watchlist-Initiationen.",
    accession: "0000886982-26-000088",
  },
  {
    id: "f9",
    ticker: "LLY",
    form: "8-K",
    filedAt: "2026-08-07T12:01:00.000Z",
    title: "Operatives Ergebnis — orale GLP-1-Kapazität",
    material: true,
    delta: "Kapazitätskommentar konstruktiver als Q1. Keine Änderung der Listenpreis-Architektur.",
    accession: "0000059478-26-000066",
  },
  {
    id: "f10",
    ticker: "MSFT",
    form: "10-Q",
    filedAt: "2026-08-01T20:22:00.000Z",
    title: "Quartalsbericht — Azure und OpenAI",
    material: false,
    delta: "Azure +33 %. Capex bekräftigt. Keine Änderung am Capital-Return-Rahmen.",
    accession: "0000789019-26-000102",
  },
];

export const SENTIMENT: SentimentRow[] = [
  {
    ticker: "TSLA",
    mentions24h: 18420,
    baseline30d: 6120,
    zscore: 3.41,
    tone: 0.42,
    flag: true,
    posts: [
      { handle: "@wholemars", text: "Unsupervised clips from the Bay Area geofence look qualitatively different from last year’s supervised build.", faves: 4200, ts: "2026-08-21T02:11:00.000Z" },
      { handle: "@teslaownersSV", text: "Three separate unsupervised drop-offs filmed tonight. This is the volume spike.", faves: 1880, ts: "2026-08-21T01:44:00.000Z" },
      { handle: "@garyblack00", text: "Signal is real. Still a 2027 P&L story. Do not pay 2028 multiples tonight.", faves: 960, ts: "2026-08-20T23:18:00.000Z" },
    ],
  },
  {
    ticker: "NVDA",
    mentions24h: 9900,
    baseline30d: 8700,
    zscore: 0.54,
    tone: 0.22,
    flag: false,
    posts: [
      { handle: "@semianalysis", text: "Take-or-pay 8-K is the tell. Hyperscalers are underwriting wafers, not just forecasts.", faves: 3100, ts: "2026-08-21T03:02:00.000Z" },
      { handle: "@dylan522p", text: "Reserved capacity is a different contract. This is how you get five-day drift.", faves: 1400, ts: "2026-08-21T02:40:00.000Z" },
    ],
  },
  {
    ticker: "META",
    mentions24h: 7400,
    baseline30d: 5100,
    zscore: 1.12,
    tone: -0.31,
    flag: false,
    posts: [
      { handle: "@justinkan", text: "Reality Labs still a $5B hole. Ads-attach is the only thing that makes the 10-Q readable.", faves: 870, ts: "2026-08-20T22:15:00.000Z" },
      { handle: "@ebinv", text: "Tone on the Q&A was worse than the print. Watch the multiple, not the beat.", faves: 540, ts: "2026-08-20T21:48:00.000Z" },
    ],
  },
  {
    ticker: "AVGO",
    mentions24h: 4100,
    baseline30d: 2800,
    zscore: 1.48,
    tone: 0.36,
    flag: false,
    posts: [{ handle: "@techtrades", text: "Hock actually named XPUs this time. That’s the sentence the buy-side wanted.", faves: 620, ts: "2026-08-20T20:11:00.000Z" }],
  },
  {
    ticker: "LLY",
    mentions24h: 3600,
    baseline30d: 3900,
    zscore: -0.22,
    tone: 0.18,
    flag: false,
    posts: [{ handle: "@biopharmadive", text: "Oral GLP-1 capacity is the whole debate. The 8-K was as constructive as Lilly gets.", faves: 410, ts: "2026-08-20T16:04:00.000Z" }],
  },
  {
    ticker: "UNH",
    mentions24h: 5200,
    baseline30d: 2100,
    zscore: 2.71,
    tone: -0.48,
    flag: true,
    posts: [
      { handle: "@healthcap", text: "MCR 88.4. Utilization “persistent.” This is not a one-quarter story.", faves: 1500, ts: "2026-08-20T15:22:00.000Z" },
      { handle: "@2sigmawatch", text: "13F shows Two Sigma already leaving. The tape is late to that.", faves: 880, ts: "2026-08-20T14:55:00.000Z" },
    ],
  },
  {
    ticker: "BLK",
    mentions24h: 2100,
    baseline30d: 1800,
    zscore: 0.41,
    tone: 0.19,
    flag: false,
    posts: [{ handle: "@etfstream", text: "iShares AUM print is the whole BLK story. Fee rate held. That’s the tollbooth.", faves: 380, ts: "2026-08-20T17:12:00.000Z" }],
  },
  { ticker: "SPY", mentions24h: 6400, baseline30d: 6100, zscore: 0.18, tone: 0.06, flag: false, posts: [] },
  { ticker: "VOO", mentions24h: 900, baseline30d: 850, zscore: 0.12, tone: 0.05, flag: false, posts: [] },
  { ticker: "AAPL", mentions24h: 4300, baseline30d: 4500, zscore: -0.11, tone: 0.04, flag: false, posts: [] },
  { ticker: "MSFT", mentions24h: 3900, baseline30d: 4100, zscore: -0.18, tone: 0.12, flag: false, posts: [] },
];

export const FUNDS = [
  "BlackRock",
  "Vanguard Group",
  "Bridgewater Associates",
  "Renaissance Technologies",
  "Citadel Advisors",
  "Two Sigma",
  "Third Point",
  "Tiger Global",
  "D.E. Shaw",
  "Millennium Management",
] as const;

export const WHALES: WhalePosition[] = [
  { id: "w1", fund: "Citadel Advisors", ticker: "LLY", shares: 1_420_000, priorShares: 0, valueMm: 1128, changePct: 100, action: "new" },
  { id: "w2", fund: "Citadel Advisors", ticker: "NVDA", shares: 18_400_000, priorShares: 15_600_000, valueMm: 3283, changePct: 17.9, action: "add" },
  { id: "w3", fund: "Citadel Advisors", ticker: "MSFT", shares: 6_200_000, priorShares: 6_050_000, valueMm: 2659, changePct: 2.5, action: "hold" },
  { id: "w4", fund: "Millennium Management", ticker: "LLY", shares: 2_100_000, priorShares: 1_650_000, valueMm: 1668, changePct: 27.3, action: "add" },
  { id: "w5", fund: "Millennium Management", ticker: "AAPL", shares: 9_800_000, priorShares: 11_200_000, valueMm: 2264, changePct: -12.5, action: "trim" },
  { id: "w6", fund: "Millennium Management", ticker: "AVGO", shares: 3_400_000, priorShares: 2_900_000, valueMm: 1062, changePct: 17.2, action: "add" },
  { id: "w7", fund: "Two Sigma", ticker: "UNH", shares: 1_120_000, priorShares: 1_620_000, valueMm: 350, changePct: -30.9, action: "trim" },
  { id: "w8", fund: "Two Sigma", ticker: "COIN", shares: 0, priorShares: 2_400_000, valueMm: 0, changePct: -100, action: "exit" },
  { id: "w9", fund: "Two Sigma", ticker: "GOOGL", shares: 5_500_000, priorShares: 5_100_000, valueMm: 962, changePct: 7.8, action: "add" },
  { id: "w10", fund: "Tiger Global", ticker: "LLY", shares: 890_000, priorShares: 640_000, valueMm: 707, changePct: 39.1, action: "add" },
  { id: "w11", fund: "Tiger Global", ticker: "META", shares: 4_200_000, priorShares: 4_800_000, valueMm: 2278, changePct: -12.5, action: "trim" },
  { id: "w12", fund: "Bridgewater Associates", ticker: "JPM", shares: 7_100_000, priorShares: 6_900_000, valueMm: 1552, changePct: 2.9, action: "hold" },
  { id: "w13", fund: "Bridgewater Associates", ticker: "UNH", shares: 2_400_000, priorShares: 2_550_000, valueMm: 751, changePct: -5.9, action: "hold" },
  { id: "w14", fund: "Renaissance Technologies", ticker: "NVDA", shares: 3_200_000, priorShares: 2_400_000, valueMm: 571, changePct: 33.3, action: "add" },
  { id: "w15", fund: "Renaissance Technologies", ticker: "TSLA", shares: 1_800_000, priorShares: 2_200_000, valueMm: 448, changePct: -18.2, action: "trim" },
  { id: "w16", fund: "Third Point", ticker: "AMZN", shares: 2_900_000, priorShares: 2_100_000, valueMm: 569, changePct: 38.1, action: "add" },
  { id: "w17", fund: "D.E. Shaw", ticker: "MSFT", shares: 4_400_000, priorShares: 4_350_000, valueMm: 1887, changePct: 1.1, action: "hold" },
  { id: "w18", fund: "D.E. Shaw", ticker: "AVGO", shares: 1_600_000, priorShares: 1_150_000, valueMm: 500, changePct: 39.1, action: "add" },
  { id: "w19", fund: "BlackRock", ticker: "MSFT", shares: 62_400_000, priorShares: 60_100_000, valueMm: 26763, changePct: 3.8, action: "add" },
  { id: "w20", fund: "BlackRock", ticker: "NVDA", shares: 48_200_000, priorShares: 44_000_000, valueMm: 8600, changePct: 9.5, action: "add" },
  { id: "w21", fund: "BlackRock", ticker: "SPY", shares: 12_800_000, priorShares: 12_400_000, valueMm: 7199, changePct: 3.2, action: "hold" },
  { id: "w22", fund: "Vanguard Group", ticker: "AAPL", shares: 71_200_000, priorShares: 70_400_000, valueMm: 16451, changePct: 1.1, action: "hold" },
  { id: "w23", fund: "Vanguard Group", ticker: "MSFT", shares: 58_900_000, priorShares: 57_200_000, valueMm: 25262, changePct: 3.0, action: "add" },
  { id: "w24", fund: "Vanguard Group", ticker: "BLK", shares: 9_400_000, priorShares: 8_700_000, valueMm: 8913, changePct: 8.0, action: "add" },
];

export const EARNINGS: EarningsNote[] = [
  {
    ticker: "AVGO",
    date: "2026-08-18",
    ceoTone: 0.62,
    cfoTone: 0.48,
    epsActual: 1.69,
    epsCons: 1.57,
    revActualB: 16.4,
    revConsB: 15.8,
    guidance: "raised",
    qa: [
      { analyst: "Ross Seymore, Deutsche Bank", exchange: "Hakte Hock auf XPU-Mix vs. Networking-ASICs. Antwort präziser als im Vorquartal — zwei Hyperscaler-Programme namentlich." },
      { analyst: "Harlan Sur, JPMorgan", exchange: "Bruttomargen-Brücke. CFO ging Custom-Silicon-Mix vs. VMware mit weniger Absicherung als in Q1 durch." },
      { analyst: "Vivek Arya, BofA", exchange: "Fragte, ob reservierte Kapazität Take-or-pay sei. Hock: „Der Kunde zahlt für Wafer, ob er sie lädt oder nicht.“" },
    ],
    summary:
      "Networking-ASIC +38 % y/y. FY-Umsatz-Guide um 2,4 Mrd. angehoben. CEO-Ton der expliziteste zu Custom-XPUs in den letzten vier Prints.",
  },
  {
    ticker: "UNH",
    date: "2026-08-15",
    ceoTone: -0.12,
    cfoTone: -0.34,
    epsActual: 4.08,
    epsCons: 4.51,
    revActualB: 113.2,
    revConsB: 112.4,
    guidance: "maintained",
    qa: [
      { analyst: "Justin Lake, Wolfe", exchange: "MCR 88,4 gegen 86,9. CFO nannte MA-Utilization „persistent“, dann vier Minuten Coding-Intensität." },
      { analyst: "Lisa Gill, JPMorgan", exchange: "Warum der FY-Guide nach dem Miss steht. Antwort stützte sich auf Optum-Erholung, nicht auf das Insurance-Book." },
      { analyst: "Kevin Fischbeck, BofA", exchange: "Fragte, ob 2027 ein Reset-Jahr sei. CEO lehnte es ab, den Langfrist-Algorithmus umzuformulieren." },
    ],
    summary: "Umsatz im Rahmen, EPS-Miss über die Medical-Cost-Ratio. Guide bestätigt. CEO-Ton flach; CFO defensiv.",
  },
  {
    ticker: "LLY",
    date: "2026-08-07",
    ceoTone: 0.44,
    cfoTone: 0.31,
    epsActual: 6.28,
    epsCons: 5.96,
    revActualB: 15.9,
    revConsB: 15.4,
    guidance: "raised",
    qa: [
      { analyst: "Chris Schott, JPMorgan", exchange: "Orale GLP-1-Kapazität. Konstruktivste Antwort in vier Quartalen — Dual-Site Fill/Finish für H2 on track." },
      { analyst: "Seamus Fernandez, Guggenheim", exchange: "Preisarchitektur. Keine Änderung — das ist selbst die Nachricht gegen den Rebate-Bill-Lärm." },
      { analyst: "Tim Anderson, BofA", exchange: "Tirzepatid vs. oral. Management lehnte ein Kannibalisierungs-Frame ab; behandelte es als Kapazitäts-Stack." },
    ],
    summary: "Sauberer Beat, Guide angehoben. Constraint bleibt Kapazität, nicht Nachfrage.",
  },
  {
    ticker: "BLK",
    date: "2026-08-08",
    ceoTone: 0.28,
    cfoTone: 0.22,
    epsActual: 11.48,
    epsCons: 11.21,
    revActualB: 5.4,
    revConsB: 5.2,
    guidance: "maintained",
    qa: [
      { analyst: "Alexander Blostein, Goldman", exchange: "iShares-AUM +9 % q/q. Fee-Rate gehalten. Management weigerte sich, einen Preiskampf zu frame'n." },
      { analyst: "Brennan Hawken, UBS", exchange: "Private-Markets-Mix. Beitrag wächst, ist aber nicht der Satz, der die 15-%-Sleeve trägt — das ist iShares." },
      { analyst: "Patrick Davitt, Autonomous", exchange: "Buyback vs. AUM-Wachstum. CFO: Capital Return unverändert, Wachstum kommt über Flow." },
    ],
    summary:
      "Sauberer Beat über AUM, nicht über Fee-Rate. Tollbooth-These: BlackRock verdient, wenn SPY/VOO-Zuflüsse laufen.",
  },
  {
    ticker: "NVDA",
    date: "2026-08-27",
    ceoTone: 0,
    cfoTone: 0,
    epsActual: 0,
    epsCons: 1.01,
    revActualB: 0,
    revConsB: 46.2,
    guidance: "maintained",
    qa: [],
    summary:
      "Print nächsten Mittwoch nach Börsenschluss. Demo-Woche läuft vor dem Print — kein Live-Add ohne grüne Demo.",
  },
];

export const MACRO: MacroEvent[] = [
  {
    id: "m1",
    when: "2026-08-24T14:00:00.000Z",
    type: "SPEECH",
    title: "Jackson Hole — Chair eröffnet das Symposium",
    implication:
      "Falls der Chair hawkish auf den Policy-Rate-Pfad geht, hat der Halbleiterkorb (NVDA, AVGO) eine implizierte Bewegung von 2,4 %. SPY/VOO als Ballast halten. Overlay-Adds erst nach der Rede.",
    watchlistMovePct: 2.4,
    flagged: true,
  },
  {
    id: "m2",
    when: "2026-08-28T12:30:00.000Z",
    type: "GDP",
    title: "Q2-BIP, zweite Schätzung",
    implication: "Street bei 2,4 %. Ein Print unter 2 würde September-Cut-Odds vorziehen und ist ein moderater Rückenwind für Duration (LLY, BLK, Mega-Cap-Growth).",
    watchlistMovePct: 0.7,
    flagged: false,
  },
  {
    id: "m3",
    when: "2026-09-04T12:30:00.000Z",
    type: "NFP",
    title: "August Nonfarm Payrolls",
    implication:
      "Watchlist-Beta auf einen 50k-Miss: rund 1,6 % bei Banken (JPM, GS) und rund 2,1 % im Overlay. Kern (SPY/VOO) fängt den Rest.",
    watchlistMovePct: 2.1,
    flagged: true,
  },
  {
    id: "m4",
    when: "2026-09-11T12:30:00.000Z",
    type: "CPI",
    title: "August-CPI",
    implication: "Core-Street 0,2 % m/m. Ein klebriger 0,3-Print in den September-FOMC bewegt das Overlay um mehr als 2 %. Kern bleibt die erste Verteidigung.",
    watchlistMovePct: 1.8,
    flagged: false,
  },
  {
    id: "m5",
    when: "2026-09-16T18:00:00.000Z",
    type: "FOMC",
    title: "September-FOMC-Entscheidung und SEP",
    implication: "Dots und Pressekonferenz, nicht die 25 bp. Ein Hold würde Semis, BLK-Duration und Long-Duration-Biopharma gappen.",
    watchlistMovePct: 2.8,
    flagged: true,
  },
  {
    id: "m6",
    when: "2026-09-11T12:30:00.000Z",
    type: "PPI",
    title: "August-PPI",
    implication: "Meist Nebenschauplatz zum CPI in derselben Woche. Nur flaggen, wenn Supercore-Services überraschen.",
    watchlistMovePct: 0.4,
    flagged: false,
  },
];

export const OPS_TASKS: OpsTask[] = [
  {
    id: "o1",
    kind: "lp",
    title: "August-LP-Brief — Erstfassung",
    status: "drafted",
    preview:
      "Month-to-date steht das Book bei +1,7 % gegen +1,4 % im S&P 500. Kern jetzt SPY/VOO/BLK. Overlay: AVGO-Add, LLY-Cluster, 40-bp-UNH-Trim. Einnahmen-Ziel ist die erste Zeile.",
  },
  {
    id: "o2",
    kind: "invoice",
    title: "Bloomberg Terminal — August-Seat",
    status: "queued",
    preview: "Vendor: Bloomberg Finance L.P. Betrag: 27.480 $. Kostenstelle: Research. Fällig: 31.08.2026.",
  },
  {
    id: "o3",
    kind: "invoice",
    title: "FactSet-Workstation-Verlängerung",
    status: "queued",
    preview: "Vendor: FactSet Research Systems. Betrag: 14.200 $. Gauge: Seat kündigen, sobald Filings- und Flows-Bots ein volles Quartal stehen.",
  },
  {
    id: "o4",
    kind: "calendar",
    title: "Woche ab 24. August — Desk-Kalender",
    status: "drafted",
    preview: "Mo: Jackson-Hole-Open, Chart-Desk Pflicht. Mi: Demo-Woche vor NVDA-Print. So: Weekly Forge/Gauge/Canon.",
  },
  {
    id: "o5",
    kind: "intel",
    title: "Newsletter-Extrakt — Woche 34",
    status: "drafted",
    preview:
      "Aus acht Research-Mails: (1) Reserved-Capacity von NVDA zu AVGO, (2) MA-Utilization mean-revertet nicht, (3) iShares-AUM trägt BLK, (4) orales GLP-1 bleibt Kapazität.",
  },
  {
    id: "o6",
    kind: "coord",
    title: "Slack: Pulse → Helmsman-Handoff",
    status: "sent",
    preview: "Pulse flaggte TSLA +3,4σ. Helmsman als Beobachten. Forge hat denselben Fehler aus Demo W32 danebengelegt.",
  },
  {
    id: "o7",
    kind: "coord",
    title: "Inklusion: Chart-Desk in Overnight-Handoff",
    status: "queued",
    preview: "Canon: vor jedem Overlay-Add 1W/1M im Chart-Desk. Owner Canon, ETA Montag 06:00 MET.",
  },
];
