import type { Agent, Insight, ProfileProposal, TradeIdea, TradeTrial } from "./types";

export const TRADE_BOTS: Agent[] = [
  {
    id: "cart",
    name: "Cart",
    desk: "trade",
    vertical: "Konsum",
    status: "done",
    lastRun: "2026-08-21T10:40:00.000Z",
    summary:
      "US-Konsum: Delinquenz Kreditkarte steigt, aber High-Income-Ticket (AAPL, AMZN-Prime) hält. UNH Care-Cost bleibt der contra-Konsum-Hedge. Kein Discretionary-Add vor NFP.",
  },
  {
    id: "signal",
    name: "Signal",
    desk: "trade",
    vertical: "Social",
    status: "alert",
    lastRun: "2026-08-21T10:42:00.000Z",
    summary:
      "X: TSLA +3,4σ, Robotaxi. Das ist Lärm — Pulse hat denselben Spike, Forge hat ihn in W32 verbrannt. Was andere übersehen: AVGO-Networking-Threads ohne Ticker, nur 'custom ASIC'. Das ist der Inside.",
  },
  {
    id: "till",
    name: "Till",
    desk: "trade",
    vertical: "Banken",
    status: "done",
    lastRun: "2026-08-21T10:44:00.000Z",
    summary:
      "NII-Stabilität JPM/GS. Credit-Spread eng. GS +3,7 % Freitag ist Event, nicht Regime. Dividende beider Namen trägt den Monat. Add nur auf Schwäche, nicht auf den Print.",
  },
  {
    id: "drift",
    name: "Drift",
    desk: "trade",
    vertical: "Trends",
    status: "done",
    lastRun: "2026-08-21T10:46:00.000Z",
    summary:
      "Inference vor Training. AVGO vor NVDA auf 3-Monats-RS. Gold (GLD) als stiller Bid, nicht als Trade. MSCI World (URTH) folgt SPY 1:1 — kein Extra-Alpha, nur Bestätigung.",
  },
  {
    id: "vein",
    name: "Vein",
    desk: "trade",
    vertical: "Insides",
    status: "done",
    lastRun: "2026-08-21T10:48:00.000Z",
    summary:
      "Was die Häuser nicht schreiben: BLK-iShares-Flow in URTH, nicht nur in SPY. Dieselbe Tollbooth, zweite Röhre. Form-4 AVGO drei Direktoren, unabhängig — Cluster, kein CEO-Sale.",
  },
  {
    id: "skipper",
    name: "Skipper",
    desk: "trade",
    vertical: "Stabschef",
    status: "done",
    lastRun: "2026-08-21T10:50:00.000Z",
    summary:
      "Koordinaten: 350 € ist der Boden, nicht das Ziel. Stretch 700, Horizont 1.500. Duales Mandat — Cash diesen Monat, Kapital über 90 Tage. Overlay nur nach Chart, Demo und Zahler-Test. Abbruch, sobald die Monatsprojektion unter 350 fällt.",
  },
];

export const TRADE_FEEDBACK_BOTS: Agent[] = [
  {
    id: "anvil",
    name: "Anvil",
    desk: "trade",
    vertical: "Trade-Post-Mortem",
    status: "done",
    lastRun: "2026-08-21T10:52:00.000Z",
    summary:
      "Trading-Demo T-JPM: 60/40-Korrektur hat in der Replay-Woche +0,5 % gegen SPY +0,3 % gemacht. T-MS noch nicht geschickt — AI-Basket ohne Kern ist W32 in größer.",
  },
  {
    id: "caliper",
    name: "Caliper",
    desk: "trade",
    vertical: "Trade-Effizienz",
    status: "done",
    lastRun: "2026-08-21T10:54:00.000Z",
    summary:
      "Signal und Pulse lesen denselben TSLA-Spike. Eine Quelle, ein Alert. Cart und Callbook dürfen Konsum/UNH teilen, nicht duplizieren. Schulung nur auf Knopf, nie im Page-Load.",
  },
  {
    id: "edict",
    name: "Edict",
    desk: "trade",
    vertical: "Profil / Weekly",
    status: "done",
    lastRun: "2026-08-21T10:56:00.000Z",
    summary:
      "Profilvorschläge Woche 35: Vein behalten (Insides zahlen), Discretionary-Sleeve nicht aufmachen, FactSet weiter auf der Kippe. Alles ins Weekly, nichts still.",
  },
];

export const TRADE_IDEAS: TradeIdea[] = [
  {
    id: "ti-avgo",
    bot: "drift",
    ticker: "AVGO",
    side: "long",
    thesis: "3M-RS vor NVDA, Guide angehoben, Form-4-Cluster. Zahler.",
    cashNow: "Dividende + Demo-Add füllt die 63-€-Lücke, wenn die Watch grün schließt.",
    capital: "Overlay-Kernname über 90 Tage. Nicht über dem 3-Sitzungs-Hoch.",
    status: "open",
  },
  {
    id: "ti-jpm",
    bot: "till",
    ticker: "JPM",
    side: "long",
    thesis: "NII stabil, 2,1 % Yield, Duration-Hedge im Overlay.",
    cashNow: "Monatszahler. Nicht jagen nach Freitag +3,7 % GS — JPM ruhiger Einstieg.",
    capital: "Banken-Satellit, 6 % Sleeve halten.",
    status: "in-demo",
  },
  {
    id: "ti-gld",
    bot: "vein",
    ticker: "GLD",
    side: "flat",
    thesis: "Stiller Bid, kein Alpha gegen den 350-€-Boden.",
    cashNow: "Gold zahlt keine Ausschüttung. Nicht in den Monat.",
    capital: "Hedge-Kandidat nach Jackson Hole, max 5 %, nur nach Mandat-Score.",
    status: "killed",
  },
  {
    id: "ti-tsla",
    bot: "signal",
    ticker: "TSLA",
    side: "flat",
    thesis: "Social-Spike, kein Filing. Lesson W32.",
    cashNow: "Null Yield, null Boden.",
    capital: "0,5 % halten, nicht addieren.",
    status: "killed",
  },
];

export const TRADE_TRIALS: TradeTrial[] = [
  {
    id: "tt-jpm",
    week: "T-JPM",
    source: "mandate",
    sourceId: "jpm-6040",
    label: "JPM 60/40 korrigiert",
    startedAt: "2026-08-15T00:00:00.000Z",
    bookPct: 0.5,
    spyPct: 0.3,
    relativePct: 0.2,
    hit: true,
    note: "Bonds auf 10 %, Zahler rein. Replay 15.–21. Aug. Grün gegen SPY. Noch nicht live — eine Woche ist keine 10J-Quote.",
  },
  {
    id: "tt-vg",
    week: "T-VG",
    source: "mandate",
    sourceId: "vg-tr",
    label: "Vanguard Target ohne Bonds",
    startedAt: "2026-08-08T00:00:00.000Z",
    bookPct: 1.0,
    spyPct: 0.5,
    relativePct: 0.5,
    hit: true,
    note: "Entspricht unserem Kern-Satellit. Bestätigt die 35/15/50-Hülle. Applied.",
  },
];

export const INSIGHTS: Insight[] = [
  {
    id: "in-1",
    at: "2026-08-21T10:42:00.000Z",
    team: "trade",
    bot: "signal",
    kind: "overlooked",
    heading: "AVGO ohne Ticker in ASIC-Threads",
    body: "Custom-ASIC-Diskussionen auf X nennen Broadcom nicht. Volumen unter der 3σ-Schwelle, deshalb hat Pulse es nicht geflaggt. Das ist der Inside, kein Mention-Spike.",
    tickers: ["AVGO"],
    weight: "high",
  },
  {
    id: "in-2",
    at: "2026-08-21T10:48:00.000Z",
    team: "trade",
    bot: "vein",
    kind: "overlooked",
    heading: "iShares-Flow in URTH, nicht nur SPY",
    body: "BLK verdient an MSCI-World-Hüllen genauso. URTH-Zufluss ist dieselbe Maut. Universum-Desk muss URTH neben SPY liegen haben.",
    tickers: ["BLK", "URTH", "SPY"],
    weight: "high",
  },
  {
    id: "in-3",
    at: "2026-08-21T10:40:00.000Z",
    team: "trade",
    bot: "cart",
    kind: "fresh",
    heading: "Karten-Delinquenz vs. High-Income-Ticket",
    body: "Latest: US-Kartenrückstände oben, Prime- und iPhone-Ticket nicht. Discretionary-Basket bleibt zu — AAPL nicht addieren, AMZN nicht auf 2 % hoch.",
    tickers: ["AAPL", "AMZN"],
    weight: "mid",
  },
  {
    id: "in-4",
    at: "2026-08-21T10:44:00.000Z",
    team: "trade",
    bot: "till",
    kind: "fresh",
    heading: "NII-Kommentar JPM vor Jackson Hole",
    body: "Latest hoher Wichtigkeit: JPM hält NII-Guide. Das trägt die Dividende durch die Event-Woche. Add erst nach der Rede.",
    tickers: ["JPM", "GS"],
    weight: "high",
  },
  {
    id: "in-5",
    at: "2026-08-21T10:35:00.000Z",
    team: "mandate",
    bot: "audit",
    kind: "fresh",
    heading: "MS AI-Leaders ohne Kern",
    body: "Häuserplan vom 4. Aug. Sechs Duration-Zwillinge. 10J-Hit 60 %, Drawdown −28 %. Nicht live, Korrektur zuerst in die Demo.",
    tickers: ["NVDA", "AVGO", "MSFT"],
    weight: "high",
  },
];

export const PROFILE_PROPOSALS: ProfileProposal[] = [
  {
    id: "pp-1",
    team: "trade",
    kind: "add",
    profile: "Vein / overlooked insides",
    rationale: "ASIC-Threads und URTH-Flow waren nicht im Research-Raster. Profil behalten, wöchentlich schulen.",
    owner: "edict",
    status: "applied",
  },
  {
    id: "pp-2",
    team: "trade",
    kind: "remove",
    profile: "Discretionary-Konsum-Sleeve",
    rationale: "Cart sieht Delinquenz. AAPL/AMZN zahlen den Boden nicht. Sleeve nicht aufmachen.",
    owner: "cart",
    status: "applied",
  },
  {
    id: "pp-3",
    team: "mandate",
    kind: "expand",
    profile: "Broker-Modellportfolios (Schwab, Fidelity)",
    rationale: "IB-Seite steht. Broker-Target-Date und SMA-Hüllen fehlen. Scout kann dieselben Fehler (Duration, keine Zahler) in einer Woche lesen.",
    owner: "scout",
    status: "discuss",
  },
  {
    id: "pp-4",
    team: "research",
    kind: "trim",
    profile: "Pulse-TSLA-Mentions",
    rationale: "Signal deckt denselben Spike. Pulse auf 3σ-ohne-Ticker-Threads umstellen oder Pulse/Signal mergen.",
    owner: "caliper",
    status: "discuss",
  },
  {
    id: "pp-5",
    team: "feedback",
    kind: "add",
    profile: "Abbruch-Schwelle im Weekly",
    rationale: "Canon muss die 350-€-Projektion jede Woche als Go/No-Go schreiben, nicht nur die Lücke.",
    owner: "canon",
    status: "queued",
  },
  {
    id: "pp-6",
    team: "research",
    kind: "remove",
    profile: "FactSet-Seat",
    rationale: "Gauge hält die Kündigung. Filings+Flows ein Quartal ohne FactSet testen.",
    owner: "gauge",
    status: "queued",
  },
];
