/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as DeskIndexRouteImport } from './routes/_desk/index'
import { Route as DeskChartsRouteImport } from './routes/_desk/charts'
import { Route as DeskChatRouteImport } from './routes/_desk/chat'
import { Route as DeskDemoRouteImport } from './routes/_desk/demo'
import { Route as DeskEarningsRouteImport } from './routes/_desk/earnings'
import { Route as DeskFeedbackRouteImport } from './routes/_desk/feedback'
import { Route as DeskFilingsRouteImport } from './routes/_desk/filings'
import { Route as DeskFlowsRouteImport } from './routes/_desk/flows'
import { Route as DeskKommandoRouteImport } from './routes/_desk/kommando'
import { Route as DeskMacroRouteImport } from './routes/_desk/macro'
import { Route as DeskMandateRouteImport } from './routes/_desk/mandate'
import { Route as DeskOpsRouteImport } from './routes/_desk/ops'
import { Route as DeskResearchRouteImport } from './routes/_desk/research'
import { Route as DeskSentimentRouteImport } from './routes/_desk/sentiment'
import { Route as DeskTradeRouteImport } from './routes/_desk/trade'
import { Route as DeskUniverseRouteImport } from './routes/_desk/universe'

const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskChartsRoute = DeskChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => DeskRoute,
} as any)
const DeskChatRoute = DeskChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DeskRoute,
} as any)
const DeskDemoRoute = DeskDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => DeskRoute,
} as any)
const DeskEarningsRoute = DeskEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DeskRoute,
} as any)
const DeskFeedbackRoute = DeskFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DeskRoute,
} as any)
const DeskFilingsRoute = DeskFilingsRouteImport.update({
  id: '/filings',
  path: '/filings',
  getParentRoute: () => DeskRoute,
} as any)
const DeskFlowsRoute = DeskFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DeskRoute,
} as any)
const DeskKommandoRoute = DeskKommandoRouteImport.update({
  id: '/kommando',
  path: '/kommando',
  getParentRoute: () => DeskRoute,
} as any)
const DeskMacroRoute = DeskMacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => DeskRoute,
} as any)
const DeskMandateRoute = DeskMandateRouteImport.update({
  id: '/mandate',
  path: '/mandate',
  getParentRoute: () => DeskRoute,
} as any)
const DeskOpsRoute = DeskOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => DeskRoute,
} as any)
const DeskResearchRoute = DeskResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSentimentRoute = DeskSentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTradeRoute = DeskTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => DeskRoute,
} as any)
const DeskUniverseRoute = DeskUniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeskIndexRoute
  '/charts': typeof DeskChartsRoute
  '/chat': typeof DeskChatRoute
  '/demo': typeof DeskDemoRoute
  '/earnings': typeof DeskEarningsRoute
  '/feedback': typeof DeskFeedbackRoute
  '/filings': typeof DeskFilingsRoute
  '/flows': typeof DeskFlowsRoute
  '/kommando': typeof DeskKommandoRoute
  '/macro': typeof DeskMacroRoute
  '/mandate': typeof DeskMandateRoute
  '/ops': typeof DeskOpsRoute
  '/research': typeof DeskResearchRoute
  '/sentiment': typeof DeskSentimentRoute
  '/trade': typeof DeskTradeRoute
  '/universe': typeof DeskUniverseRoute
}
export interface FileRoutesByTo {
  '/charts': typeof DeskChartsRoute
  '/chat': typeof DeskChatRoute
  '/demo': typeof DeskDemoRoute
  '/earnings': typeof DeskEarningsRoute
  '/feedback': typeof DeskFeedbackRoute
  '/filings': typeof DeskFilingsRoute
  '/flows': typeof DeskFlowsRoute
  '/kommando': typeof DeskKommandoRoute
  '/macro': typeof DeskMacroRoute
  '/mandate': typeof DeskMandateRoute
  '/ops': typeof DeskOpsRoute
  '/research': typeof DeskResearchRoute
  '/sentiment': typeof DeskSentimentRoute
  '/trade': typeof DeskTradeRoute
  '/universe': typeof DeskUniverseRoute
  '/': typeof DeskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desk': typeof DeskRouteWithChildren
  '/_desk/charts': typeof DeskChartsRoute
  '/_desk/chat': typeof DeskChatRoute
  '/_desk/demo': typeof DeskDemoRoute
  '/_desk/earnings': typeof DeskEarningsRoute
  '/_desk/feedback': typeof DeskFeedbackRoute
  '/_desk/filings': typeof DeskFilingsRoute
  '/_desk/flows': typeof DeskFlowsRoute
  '/_desk/kommando': typeof DeskKommandoRoute
  '/_desk/macro': typeof DeskMacroRoute
  '/_desk/mandate': typeof DeskMandateRoute
  '/_desk/ops': typeof DeskOpsRoute
  '/_desk/research': typeof DeskResearchRoute
  '/_desk/sentiment': typeof DeskSentimentRoute
  '/_desk/trade': typeof DeskTradeRoute
  '/_desk/universe': typeof DeskUniverseRoute
  '/_desk/': typeof DeskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charts'
    | '/chat'
    | '/demo'
    | '/earnings'
    | '/feedback'
    | '/filings'
    | '/flows'
    | '/kommando'
    | '/macro'
    | '/mandate'
    | '/ops'
    | '/research'
    | '/sentiment'
    | '/trade'
    | '/universe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/charts'
    | '/chat'
    | '/demo'
    | '/earnings'
    | '/feedback'
    | '/filings'
    | '/flows'
    | '/kommando'
    | '/macro'
    | '/mandate'
    | '/ops'
    | '/research'
    | '/sentiment'
    | '/trade'
    | '/universe'
    | '/'
  id:
    | '__root__'
    | '/_desk'
    | '/_desk/charts'
    | '/_desk/chat'
    | '/_desk/demo'
    | '/_desk/earnings'
    | '/_desk/feedback'
    | '/_desk/filings'
    | '/_desk/flows'
    | '/_desk/kommando'
    | '/_desk/macro'
    | '/_desk/mandate'
    | '/_desk/ops'
    | '/_desk/research'
    | '/_desk/sentiment'
    | '/_desk/trade'
    | '/_desk/universe'
    | '/_desk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeskRoute: typeof DeskRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/': {
      id: '/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/charts': {
      id: '/_desk/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof DeskChartsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/chat': {
      id: '/_desk/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof DeskChatRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/demo': {
      id: '/_desk/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DeskDemoRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/earnings': {
      id: '/_desk/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof DeskEarningsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/feedback': {
      id: '/_desk/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof DeskFeedbackRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/filings': {
      id: '/_desk/filings'
      path: '/filings'
      fullPath: '/filings'
      preLoaderRoute: typeof DeskFilingsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/flows': {
      id: '/_desk/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof DeskFlowsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/kommando': {
      id: '/_desk/kommando'
      path: '/kommando'
      fullPath: '/kommando'
      preLoaderRoute: typeof DeskKommandoRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/macro': {
      id: '/_desk/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof DeskMacroRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/mandate': {
      id: '/_desk/mandate'
      path: '/mandate'
      fullPath: '/mandate'
      preLoaderRoute: typeof DeskMandateRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/ops': {
      id: '/_desk/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof DeskOpsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/research': {
      id: '/_desk/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof DeskResearchRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/sentiment': {
      id: '/_desk/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof DeskSentimentRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/trade': {
      id: '/_desk/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof DeskTradeRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/universe': {
      id: '/_desk/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof DeskUniverseRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskChartsRoute: typeof DeskChartsRoute
  DeskChatRoute: typeof DeskChatRoute
  DeskDemoRoute: typeof DeskDemoRoute
  DeskEarningsRoute: typeof DeskEarningsRoute
  DeskFeedbackRoute: typeof DeskFeedbackRoute
  DeskFilingsRoute: typeof DeskFilingsRoute
  DeskFlowsRoute: typeof DeskFlowsRoute
  DeskKommandoRoute: typeof DeskKommandoRoute
  DeskMacroRoute: typeof DeskMacroRoute
  DeskMandateRoute: typeof DeskMandateRoute
  DeskOpsRoute: typeof DeskOpsRoute
  DeskResearchRoute: typeof DeskResearchRoute
  DeskSentimentRoute: typeof DeskSentimentRoute
  DeskTradeRoute: typeof DeskTradeRoute
  DeskUniverseRoute: typeof DeskUniverseRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskChartsRoute: DeskChartsRoute,
  DeskChatRoute: DeskChatRoute,
  DeskDemoRoute: DeskDemoRoute,
  DeskEarningsRoute: DeskEarningsRoute,
  DeskFeedbackRoute: DeskFeedbackRoute,
  DeskFilingsRoute: DeskFilingsRoute,
  DeskFlowsRoute: DeskFlowsRoute,
  DeskKommandoRoute: DeskKommandoRoute,
  DeskMacroRoute: DeskMacroRoute,
  DeskMandateRoute: DeskMandateRoute,
  DeskOpsRoute: DeskOpsRoute,
  DeskResearchRoute: DeskResearchRoute,
  DeskSentimentRoute: DeskSentimentRoute,
  DeskTradeRoute: DeskTradeRoute,
  DeskUniverseRoute: DeskUniverseRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeskRoute: DeskRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
